name: Build
on: [push, pull_request]
jobs:
  build_matrix:
    strategy:
      matrix:
        preset: ["debug", "release"]
        os: ["ubuntu-latest", "windows-latest"]
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v4
      - name: configure
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{matrix.preset}}'
          buildPreset: 'eta-hsm-${{matrix.preset}}'

        