name: Check Format C++
on: [push, pull_request]
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '13'
          check-path: 'cpp'
